package sv.com.seguridadcontrol.app.modelos

data class Advisers(
    val data: List<Adviser>,
    val status: Boolean
)

data class AdviserData(val id_empleado: String,
                       val apellido_empleado: String,
                       val nombre_empleado: String)

data class Adviser(
    val apellido_empleado: String,
    val celular_empleado: String,
    val clave: String,
    val correo_empleado: String,
    val departamento_empresa: String,
    val direccion_empleado: String,
    val direccion_sucursal: String,
    val dui_empleado: String,
    val estado_civil_empleado: String,
    val estado_departamento_empresa: String,
    val estado_empleado: String,
    val estado_puesto_empleado: String,
    val estado_sucursal: String,
    val estado_tipo_usuario: String,
    val estado_usuario: String,
    val fecha_fin_puesto_empleado: String,
    val fecha_inicio_puesto_empleado: String,
    val fecha_nacimiento: String,
    val fin_departamento_empresa: String,
    val fin_sucursal: String,
    val foto_nombre: String,
    val id_cargo: String,
    val id_departamento_empresa: String,
    val id_empleado: String,
    val id_empresa: String,
    val id_forma_pago: String,
    val id_municipio: String,
    val id_puesto_empleado: String,
    val id_sucursal: String,
    val id_tipo_empleado: String,
    val id_tipo_usuario: String,
    val id_usuario: String,
    val id_usuario_empleado: String,
    val inicio_departamento_empresa: String,
    val inicio_sucursal: String,
    val isss_empleado: Any,
    val nacionalidad_empleado: String,
    val nit_empleado: String,
    val nombre_empleado: String,
    val numero_cuenta_empleado: String,
    val nup_empleado: String,
    val observacion: String,
    val registro_departamento_empresa: String,
    val registro_empleado: String,
    val registro_puesto_empleado: String,
    val registro_sucursal: String,
    val registro_usuario: String,
    val salario_ordinario: String,
    val sexo_empleado: String,
    val sucursal: String,
    val telefono_empleado: String,
    val tipo_afp: Any,
    val tipo_contrato: Any,
    val tipo_sucursal: String,
    val tipo_usuario: String,
    val usuario: String
)